project:
  type: website
  output-dir: docs


website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
      theme: gruvbox-dark
  title: "Inquiring Minds Want to Know"
  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Data Profolio
      - text: Side Project
        menu: 
          - text: Dang's Design
            href: dangdesign.qmd
          - text: Kid's Book
            href: buildingOM.qmd
            
      - icon: github
        href: https://github.com//rbarbanell
      - icon: linkedin
        href: https://www.linkedin.com/in/rebeccabarbanell/
      - href: Rebecca_Resume.pdf
        text: Resume
        
format:
 html:
    theme: sandstone
    toc: true
    toc-location: right
    html-math-method: katex
    number-sections: true
    category: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    mainfont: system-ui
    fontsize: 1.0 em
    linestretch: 1.7
    css: styles.css
    code-fold: true
    code-summary: "Code"
    link-external-newwindow: true



